name: Build and Deploy Cutesense Weather

on:
  push:
    branches:
      - main  # This triggers the build whenever you push to main

permissions:
  contents: write  # Necessary to push the build to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Vite builds into 'dist'
          branch: gh-pages  # The branch that will host the live site